apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  {{- if .Values.global.prometheus.enabled }}
    prometheus-alertmanager-endpoint: http://{{ .Release.Name }}-prometheus-alertmanager.{{ .Release.Namespace  }}.svc.cluster.local
  {{ else }}
    prometheus-alertmanager-endpoint: {{ .Values.global.notifications.alertmanager.fqdn }}
  {{- end -}}
  {{- if .Values.global.prometheus.enabled }}
    prometheus-server-endpoint: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace  }}.svc.cluster.local
  {{ else }}
    prometheus-server-endpoint: {{ .Values.global.prometheus.fqdn }}
  {{- end -}}
  {{- if .Values.kubecostToken }}
    kubecost-token: {{ .Values.kubecostToken }}
  {{ else }}
    kubecost-token: not-applied
  {{- end -}}