{{- if .Values.persistentVolume -}}
{{- if .Values.persistentVolume.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 0.2Gi
    {{ end }}
{{- end -}}
{{- else -}}
annotations:
  volume.beta.kubernetes.io/storage-class: portworx-sc
  volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 0.2Gi
    {{ end }}
{{- end -}}
